### ISSUE TITLE
Use column mappers in JDBI 2.70+

### ISSUE THREAD

**Issue by qualidafial** [shakiba/jdbi-annotation#3]
Pull request jdbi/jdbi#164 introduced a single-column mapper type: `ResultColumnMapper`, and exposes the registry of column mappers for use by `ResultSetMapper`s via `StatementContext.columnMapperFor(Class)`.

Using the column mapper registry would allow you to throw away `AnnoType`, and would let you automatically support annotated members for any type that has a column mapper registered.

**Comment by shakiba** [comment]
@qualidafial Thanks for letting me know, however currently I'm not actively working one this project, so please feel to fork it.

**Comment by qualidafial** [comment]
Hi @shakiba. May I have your permission to copy your code into JDBI v3, and license it under the Apache License 2.0?

**Comment by qualidafial** [comment]
Never mind, I just noticed the code is already licensed under Apache 2.0 per `pom.xml` license block. Thanks!

**Comment by shakiba** [comment]
+1
